name: FP-40-years-assistance

services:
    app_build:
        image: dental-hub-app
        command: sh -c "cp -r /app/public/* /app/public_volume"
        build:
            context: .
            dockerfile: docker/alpine_app_build.dockerfile
        volumes:
            - public_data:/app/public_volume
            - storage_data:/app/storage
        pull_policy: never
    nginx:
        image: nginx:1.27-alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - public_data:/var/www/html/public
            - storage_data:/var/www/html/storage
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - octane
    octane:
        image: dental-hub-app
        restart: unless-stopped
        entrypoint: [ "php", "artisan", "octane:frankenphp" ]
        depends_on:
            - app_build
            - postgres
        volumes:
            - storage_data:/app/storage
        pull_policy: never
    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
    artisan:
        extends:
            service: octane
        entrypoint: [ "php", "artisan" ]
        depends_on:
            - app_build
            - postgres
        volumes:
            - storage_data:/app/storage
        profiles:
            - artisan
volumes:
    public_data:
    storage_data:
    postgres_data:
